//
//  Message.swift
//  Her-Tech-Connect
//
//  Created by Natalman Nahm on 11/14/21.
//

import Foundation
import SwiftUI
import FirebaseDatabase

class Message: Identifiable {
    var senderEmail: String
    var senderName: String
    var message: String
    var type: String
    var timeCreated: Double
    var content: [String:Any] //Dictionary that stores all of the Message's content which can be accessed by calling Message.content["key for what you'd like to access"]
    static let ref = Database.database().reference()
    
    init(senderEmail: String, senderName:String, message: String, type: String) {
        
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd hh:mm:ss"
        
        self.senderEmail = senderEmail
        self.senderName = senderName
        self.message = message
        self.type = type
        self.timeCreated = Date().timeIntervalSince1970
        self.content = ["senderID":self.senderEmail,
                        "senderName":self.senderName,
                        "message":self.message,
                        "type":self.type,
                        "timeCreated":self.timeCreated
        ]
    }
    
    /*
     Send message to the recipient
     */
    func sendTo(recipientEmail: String) {
        
        Message.ref.child("ChatGroup").child(self.senderEmail).child(recipientEmail).observeSingleEvent(of: .value, with: {(recipientNode) in
            //if conversation already exists
            if recipientNode.hasChildren() {
                let recipientDictionary = recipientNode.value as! [String:String]
                let chatID = recipientDictionary["chatID"]!
                //append message to existing conversation
                Message.ref.child("Chats").child(chatID).childByAutoId().setValue(self.content)
                //else
            } else {
                //create new conversation
                Message.newChatWith(senderEmail: self.senderEmail, recipientEmail: recipientEmail)
                //retry send message
                self.sendTo(recipientEmail: recipientEmail)
            }
            
        })
    }
    
    /*
     Create a new chat
     */
    static func newChatWith(senderEmail: String, recipientEmail: String) {
        //new child node for Chats/(chatID = autogenerated)
        let newChat: [String:Any] = ["chatID": Message.ref.child("Chats").childByAutoId().key ?? " "]
        //new child node for Members/senderUserID/(recipientUserID)
        Message.ref.child("ChatGroup").child(senderEmail).child(recipientEmail).setValue(newChat)
        //new child node for Members/recipientUserID/(senderUserID)
        Message.ref.child("ChatGroup").child(senderEmail).child(recipientEmail).setValue(newChat)
    }
}
